### PR TITLE
BOSA21Q1-217 Bosa & Bosa cities: slugs of pages > add validations

### PR DESCRIPTION
**Pull request by sergei-krylov**
Remove `/` from list of allowed chars as it breaks the URL navigation and static page became broken to edit.

### CODE REVIEW

**Comment by simon-lejeune** [comment]
decidim 0.24 and develop
```
    validates :slug, format: { with: %r{\A[a-zA-Z]+[a-zA-Z0-9\-_/]+\z} }, allow_blank: true
```
decidim 0.22 (the one you're changing)
```
    validates :slug, format: { with: %r{\A[a-zA-Z]+[a-zA-Z0-9\-\_/]+\z} }, allow_blank: true
```
your version
```
    validates :slug, format: { with: %r{\A[a-zA-Z]+[a-zA-Z0-9\-\_]+\z} }, allow_blank: true
```

- any comments on why they chose to disallow the backslash and you chose to disallow the slash?
- is the bug only on decidim side or is it somehow to our custos ?
- can you reproduce it on https://decidim.org/demo/ ?

**Comment by simon-lejeune** [comment]
note: they explicitly test [here](https://github.com/decidim/decidim/blob/develop/decidim-admin/spec/forms/static_page_form_spec.rb#L109) that url pathes (including slashes) are valid slug for static page

**Comment by simon-lejeune** [comment]
i tested on 024.3 and it is working, not completely as expected because the slug "/page/1/2/3" gives back "http://localhost:3000/pages/page%2F1%2F2%2F3" but it doesn't break the the url navigation nor the page edition to me.

Can you clarify what you mean by "breaks the URL navigation and static page became broken" ?

another note: they are working on [this improvement](https://meta.decidim.org/processes/roadmap/f/122/proposals/16296?component_id=122&locale=en&order=recent&participatory_process_slug=roadmap&per_page=50) that will probably solve the issue.

**Comment by sergei-krylov** [comment]
I mean that it breaks the URL of the page, so slashes are not escaped to became "%2F", and given they stay as slashes in url the routing breaks or it can't find the proper page (example of issue: https://appsignal.com/belighted/sites/604fdfe25ac13f03e5858fff/exceptions/incidents/185)
They have tests for it, yes, and the test is for the form which accepts the slashes, so test is valid.

I've checked now on 0.24.3 and in current master for both bosa and bosa-cities apps - and I can't reproduce it locally by some reason. Checking...

**Comment by simon-lejeune** [comment]
superseded by https://github.com/belighted/bosa/pull/164

**Pull request closed without merging**
