### PR TITLE
NT: update ruby to 2.7.3

### PR DESCRIPTION
**Pull request by aokon**
Updated:

* Updated ruby to latest version of 2.7 (https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-7-3-released/) In this part I didn't update
  the docker part.

### CODE REVIEW

**Comment by aokon** [comment]
@sergei-krylov I don't know if we need to update also this part https://github.com/belighted/bosa/blob/decidim-0.24.2/ops/base/Dockerfile#L1 🤔

**Comment by sergei-krylov** [comment]
@aokon , I think we can stay on ruby 2.7.1 for now as decidim is using this version in v2.4: https://github.com/decidim/decidim/blob/v0.24.2/CHANGELOG.md#bump-ruby-to-v27
And we can follow ruby updates as decidim updates it.

Yes, we need to bump the ruby version in /ops files too, you can create a separate PR for it and ask Vlad to review that as well to make sure it will be enough for pods to update ruby version properly.

Besides that - it doesn't make too much sense to simply bump a ruby version in the app without updating it in all the modules we're using :smiley:

**Comment by aokon** [comment]
```
Besides that - it doesn't make too much sense to simply bump a ruby version in the app without updating it in all the modules we're using 😃
```
good point ☝️

**Comment by aokon** [comment]
I'm closing this PR, since we migrate to the a new ruby version when it will be updated on the decidim level,

**Pull request closed without merging**
