### PR TITLE
BOSA21Q1-505 Interactive map module shouldn't register itself as a component

### PR DESCRIPTION
**Pull request by sergei-krylov**
Changes in module: https://github.com/belighted/decidim-module-homepage_interactive_map/commit/7dc5d5c9adc978151bcf5207d9879c599f63a11a

### CODE REVIEW

**Comment by simon-lejeune** [comment]
why shouldn't the Interactive map module register itself as a component?

**Comment by sergei-krylov** [comment]
It is explained in the ticket: https://belighted.atlassian.net/browse/BOSA21Q1-505?focusedCommentId=29284
The module doesn’t implement anything to support this functionalities, and actually it doesn’t make any sense to define it as a component as there is no configuration/settings needed to be set that way.

**Comment by simon-lejeune** [comment]
a commit message should explain why the changes are made, here the commit message doesn't bring me any value over reading the diff. i don't know
- why you needed to remove the declaration as a module
- why it was first declared as a module
- what problem does this fixe solve
- what is the interaction between the changes and the problem it solve? we cannot create a petition because a module is declared as a component? what is the link?

**Review by simon-lejeune — APPROVED** [review]
changes are ok
commit message is ko

since the tech lead team did not agree on commit message guideline i'm not enforcing my policy on this pr

**Pull request merged**
