### PR TITLE
BOSA21Q1-515 Rename "Bosa Dummy Authorization" in "Bosa Authorization"

### PR DESCRIPTION
**Pull request by sergei-krylov**
Rename dummy auth handler as requested.
In addition, we hide it from user profile pages. The dummy handler is used to allow admins to impersonate users (creates authorization record when admin is impersonated), and users shouldn't see this auth handler when visiting their `/authorizations` page, or after sign up on `/authorizations/first_login` page.

### CODE REVIEW

**Comment by simon-lejeune** [comment]
can you please investigate if you could include/inherit/prepend/extend the original UserProfile module and just override the `available_verification_workflows` method ?

the goal would be to only redefine as less as possible and leave the maintenance of the remaining of this file to decidim.
as discussed, it's not that important for this specific usecase but it could be for future tasks. 

another thing is that the upstream tests sometimes reference `dummy_authorization_handler`, i fear we're going to break even more upstream tests with that change. but it's a really minor comment.

earlier you were talking about hiding this entry with a css rule, why did you chose to implement it in ruby?

**Comment by sergei-krylov** [comment]
> can you please investigate if you could include/inherit/prepend/extend the original UserProfile module and just override the available_verification_workflows method ?

Specificity of concerns is that they "includes" the code block, it takes a block and creates a `self.included` method on the current module. Code is executed in the context of the class where concern module is included in, so everything defined in the concern module will be owned by the class including the module, not by the concern module itself.

On app load, the gems are loaded into memory before our app code, the classes are defined based on the files which are loaded based on their paths. In case we do not monkey-patch the file - the original file from the gem is loaded. So, after this initial load of the code, at the moment when we execute our extends the decidims' modules/classes are already defined and loaded, and concerns already executed and "included" their code into all the other classes that including these concerns.

Basically, it is possible to make it work using concerns extends, but the effort is not worth it.
Yes we can extend a concern to include/change some code inside it, but to make it "re-include" the changed code we need to include the updated concern into the classes again. Decidim uses a lot of concerns and they're included into multiple modules and classes, and some modules with concerns included might be, in turn, included into other modules, etc.
So if we extend some concern we must create extends to all the classes that includes this concern to include it again after execution of our extend of the concern. We also should make sure we execute the concern extend before we execute our other extends of the classes.
This flow is way more complicated and might produce issues that could be hard to find, as code could be defined as an extend of concern and looks clear, but it won't work as expected and could be not executed at all, or would be executed for some classes but not for others (based on when they were defined - before the concern extend or after).
Usage of `predefine` is limited by same reasons as above.

I even put this https://github.com/belighted/bosa/blob/master/config/application.rb#L63-L71 into app load phase to avoid such issues for future.

---

> another thing is that the upstream tests sometimes reference dummy_authorization_handler, i fear we're going to break even more upstream tests with that change. but it's a really minor comment.

Yes we will break a few, but that would be expected behavior and we can update these tests to follow our changes.

---

> earlier you were talking about hiding this entry with a css rule, why did you chose to implement it in ruby?

I consider hiding it with css more like a "hack" rather than a correct change. Anyone with knowledge of css could go to dev tools in browser, make the div visible and interact with html/buttons inside it.
Also to do that with css I would need to add it to all tenants we have. Also other admins might remove/corrupt that css and it will became visible.
So, just not a perfect way. Custom css is ok for temporary changes, when we need to hide something for some period, or change colors/styles, etc.

**Comment by simon-lejeune** [comment]
Thanks for the clarifications.

I read a bit about and asked around about ruby's monkey patching strategies and i found `module_eval`.

I tested this snippet on decidim 0.24 and it is working as expected
```ruby
Decidim::UserProfile.module_eval do
  def available_verification_workflows
      Decidim::Verifications::Adapter.from_collection(
        current_organization.available_authorizations & Decidim.authorization_workflows.map(&:name).reject{|w| w == 'id_documents'}
      )
  end
end
```

I can only redefine the bit of the module i want. Do you see any drawbacks with that approach ?

Thanks

**Comment by sergei-krylov** [comment]
Yes, actually it works with `module_eval` for this particular example but not for other concerns we change.
That's because the method we're changing is defined in the module itself and not in its `included` block - that's the difference. And `ActiveSupport::Concern::MultipleIncludedBlocks` exception will be raised if we try to declare multiple `included` blocks.
For the method defined like this the same strategy works as we do for our other extends.

For other concerns we currently have we change the internals of `included` block.
Here is an example:
https://github.com/belighted/bosa/blob/master/app/controllers/concerns/decidim/initiatives/orderable.rb
The diff with original:
Screenshot
So we can't extend the method inside the `included` block as it doesn't allow to define multiple `included` blocks.
You can try to play with this simple example if you want, the change adds a new sort option to the dropdown on the `/initiatives` page.

In case we can't extend the concerns the same way as we do other extends, I prefer to have them all patched the same way and do not mix patches and extends for same/different concern(s) as it might be confusing when reading the code.

**Comment by simon-lejeune** [comment]
> In case we can't extend the concerns the same way as we do other extends, I prefer to have them all patched the same way and do not mix patches and extends for same/different concern(s) as it might be confusing when reading the code.

You can still make it work with the included block, but you need to replace it completely (cannot patch individual methods):
```ruby
Decidim::Initiatives::Orderable.send(:remove_instance_variable, :@_included_block)
Decidim::Initiatives::Orderable.module_eval do
  included do
    include Decidim::Orderable

    def available_orders
      @available_orders ||= %w(random recent most_voted most_commented recently_published answer_date)
    end

    def default_order
      "random"
    end

    def reorder(initiatives)
      case order
      when "most_voted"
        initiatives.order_by_supports
      when "most_commented"
        initiatives.order_by_most_commented
      when "recent"
        initiatives.order_by_most_recent
      when "recently_published"
        initiatives.order_by_most_recently_published
      when "answer_date"
        initiatives.order_by_answer_date
      else
        initiatives.order_randomly(random_seed)
      end
    end
  end
end
```

In that specific use case, it is useless since there isn't anything else than the included block in the file. But if it is a complex file with many other lines, the benefits are clear. I'm also curious to see if there is many changes we have already done in that `included` block.

**Comment by sergei-krylov** [comment]
But that means you remove the entire `included` block from it and adding a new block instead.
```
Decidim::Initiatives::Orderable.send(:remove_instance_variable, :@_included_block)
Decidim::Initiatives::Orderable.module_eval do
  included do
...
  end
end
```
So if there are 20 methods in included block of the original concern and I need to change 1 of these methods - I can't do that this way. Because if I remove the original block of code, define another block with only that 1 method, then I loose other 19 methods...

That doesn't make any sense then.

**Comment by simon-lejeune** [comment]
> That doesn't make any sense then.

Please read my comment? I explicitly told that you cannot patch individual methods inside included and I also told you that there are clear benefits on files where there are some other lines to be saved, outside included. This actually makes sense once you understand that included is just syntactic sugar over a method name included.

**Comment by simon-lejeune** [comment]
I can quickly define the "clear benefits" I'm talking about:
- you know at a glance what you changed from the library
- if a bug is fixed by Decidim on the methods you did not patch, you benefit
  from it directly
- if an improvement is made by Decidim on the methods you did not patch, you
  benefit from it directly
- it helps keeps the modifications from Decidim as minimal as possible
- it eases the work to do when upgrading Decidim version (you don't have to
  backport all their commits and you kept the library modifications to a low
  number)
- and possibly more I'm not thinking of right now

And yes, there is a limitation with the `included` block, so it brings these
benefits to the other parts of the files. I don't see why we should forego the
benefits of any solution because of one case where the solution isn't totally
efficient (it still is in this case, though, imagine you have 20 methods in
`included` but also 20 other normal ones).

Only patching what you need to change from a library or even another
class/module is a basic good guideline of writing sofware.

I'm not saying that `module_eval` is a silver bullet that will solves all our
issues and I'm certain it will bring its own ones, but please let's keep the
debate open on some solutions that could avoid copy pasting complete files of
Decidim in our application.

**Comment by sergei-krylov** [comment]
> Please read my comment?

Yes, definitely! 🤦‍♂️ 
Sorry, I read it wrong and thought about your example as of a possible solution 🙈.

> I can quickly define the "clear benefits" I'm talking about
Only patching what you need to change from a library or even another class/module is a basic good guideline of writing sofware.

I totally agree, I also share this opinion, and the whole purpose of initial bosa app migration was to make it so, to move all the changes to extends and keep them minimal.

For this particular case with concerns that was the only way to go at the moment, until we find a better solution.

**Review by simon-lejeune — APPROVED** [review]
Approving to move forward and also because it's in the spirit of the current codebase but I plan to start again the discussion on potentially cleaner extensions techniques to decidim

**Pull request merged**
